// Per-file import descriptors for the High Performance End Mills family.
// Columns are resolved by header NAME (see import.mjs). Per-descriptor:
//   category  — product-line slug
//   system    — Imperial | Metric
//   geometry  — Square | Ball | Corner Radius (facet; omitted where not applicable)
//   fixedFlutes — flute count when the file doesn't state it (V4/V5=6, HY5=4, F45=6, Hyper/Aluma=2)

export const MANUFACTURER_SLUG = 'mastercut-tool';

// category slug → line label used in product names
export const GEOMETRY = {
  'hp-v4-end-mills': 'V4 End Mill',
  'hp-v5-end-mills': 'V5 End Mill',
  'hp-hy5-end-mills': 'HY5 End Mill',
  'hp-f45-end-mills': 'F45 End Mill',
  'hp-axmill-end-mills': 'AxMill',
  'hp-roughers': 'Rougher',
  'hp-mold-mills': 'Mold Mill',
  'hp-twister-mills': 'Twistermill',
  'hp-hyper-mills': 'Hypermill',
  'hp-alumazips': 'Alumazip',
  'r-v-flute-straight': 'V-Flute Straight Router',
  'r-o-flute-straight': 'O-Flute Straight Router',
  'r-o-flute-straight-edge-rounding': 'O-Flute Straight Edge-Rounding Router',
  'r-o-flute-spiral-edge-rounding': 'O-Flute Spiral Edge-Rounding Router',
  'r-o-flute-upcut-spiral': 'O-Flute Upcut Spiral Router',
  'r-o-flute-downcut-spiral': 'O-Flute Downcut Spiral Router',
  'r-upcut-spiral': 'Upcut Spiral Router',
  'r-downcut-spiral': 'Downcut Spiral Router',
  'r-veining-bits': 'Veining Bit',
  'r-compression': 'Compression Router',
  'r-ball-compression': 'Ball Compression Router',
  'r-mortise-compression': 'Mortise Compression Router',
  'r-ofx-upcut': 'OFX Upcut Router',
  'r-ofx-downcut': 'OFX Downcut Router',
  'r2-upcut-spiral': 'Upcut Spiral Router',
  'r2-downcut-spiral': 'Downcut Spiral Router',
  'r2-upcut-slow': 'Upcut Slow Spiral Router',
  'r2-downcut-slow': 'Downcut Slow Spiral Router',
  'r2-o-upcut-slow': 'O-Flute Upcut Slow Spiral Router',
  'r2-o-downcut-slow': 'O-Flute Downcut Slow Spiral Router',
  'r2-upcut-chipbreaker': 'Upcut Spiral Chipbreaker Router',
  'r2-downcut-chipbreaker': 'Downcut Spiral Chipbreaker Router',
  'r2-upcut-high-impact': 'Upcut High-Impact Router',
  'r2-downcut-high-impact': 'Downcut High-Impact Router',
  'r2-upcut-chipbreaker-hi': 'Upcut Chipbreaker High-Impact Router',
  'r2-downcut-chipbreaker-hi': 'Downcut Chipbreaker High-Impact Router',
  'r2-compression': 'Compression Router',
  'r2-mortise-compression': 'Mortise Compression Router',
  'r2-chipbreaker-compression': 'Chipbreaker Compression Router',
  'r2-up-plunge': 'Upcut Plunge Router',
  'r2-downcut-fishtail': 'Downcut Fishtail Router',
  'r2-straight-plunge': 'Straight Cut Plunge Router',
  'r2-shear-v-bottom': 'Shear V-Bottom Router',
  'r2-v-edge-rounding': 'V-Flute Edge-Rounding Router',
  'r2-o-edge-rounding': 'O-Flute Edge-Rounding Router',
  'r2-rout-chamfer': 'Straight Rout & Chamfer Router',
  'r2-upcut-bottom-surface': 'Upcut Bottom-Surface Router',
  // ---- Reamers ----
  'rm-45-reamers': '45° Reamer',
  // ---- Standard Carbide Drills ----
  'dr-jobber-drills': 'Jobber Drill',
  'dr-stub-drills': 'Stub Drill',
  'dr-straight-flute-drills': 'Straight Flute Drill',
  'dr-spade-drills': 'Spade Drill',
  'dr-nc-spotting-drills': 'NC Spotting Drill',
  'dr-drill-countersink': 'Drill & Countersink',
  'dr-medium-length-drills': 'Medium Length Drill',
  // ---- Hurricane Drills (HP, 2-flute, 140° point, 30° helix) ----
  'dr-hurricane-3xd': 'Hurricane 3xD Drill',
  'dr-hurricane-5xd': 'Hurricane 5xD Drill',
  'dr-hurricane-8xd': 'Hurricane 8xD Drill',
  // ---- Carbide Burs (ANSI shapes SA–SN) ----
  'b-sa': 'Cylinder Bur',
  'b-sb': 'Cylinder End-Cut Bur',
  'b-sc': 'Cylinder Ball-Nose Bur',
  'b-sd': 'Ball Bur',
  'b-se': 'Oval Bur',
  'b-sf': 'Tree Radius-End Bur',
  'b-sg': 'Tree Pointed-End Bur',
  'b-sh': 'Flame Bur',
  'b-sj': '60° Cone Bur',
  'b-sk': '90° Cone Bur',
  'b-sl': 'Taper Radius-End Bur',
  'b-sm': 'Cone Pointed Bur',
  'b-sn': 'Inverted Cone Bur',
  'b-tire-burs': 'Tire Bur',
  'b-diemills': 'Diemill',
  'b-piloted-diemills': 'Piloted Diemill',
  'b-fiberglass-routers': 'Fiberglass Router',
};

const V = 'hp-v4-end-mills', V5 = 'hp-v5-end-mills', HY5 = 'hp-hy5-end-mills', F45 = 'hp-f45-end-mills',
  AX = 'hp-axmill-end-mills', RO = 'hp-roughers', MO = 'hp-mold-mills', TW = 'hp-twister-mills',
  HY = 'hp-hyper-mills', AL = 'hp-alumazips';
const SQ = 'Square', BA = 'Ball', CR = 'Corner Radius';

export const DESCRIPTORS = [
  // ---- V4 (flutes 6) ----
  { file: 'FRT V4 Square Endmills.csv', category: V, system: 'Imperial', geometry: SQ, fixedFlutes: 6 },
  { file: 'FRT V4 Ball Endmills.csv', category: V, system: 'Imperial', geometry: BA, fixedFlutes: 6 },
  { file: 'FRT - V4 Corner Radius.csv', category: V, system: 'Imperial', geometry: CR, fixedFlutes: 6 },
  { file: 'MET V4 Square.csv', category: V, system: 'Metric', geometry: SQ, fixedFlutes: 6 },
  { file: 'MET V4 Ball.csv', category: V, system: 'Metric', geometry: BA, fixedFlutes: 6 },
  { file: 'MET V4 Corner Radius.csv', category: V, system: 'Metric', geometry: CR, fixedFlutes: 6 },
  // ---- V5 (flutes 6) ----
  { file: 'FRT V5 Square End.csv', category: V5, system: 'Imperial', geometry: SQ, fixedFlutes: 6 },
  { file: 'FRT V5 Ball Endmills.csv', category: V5, system: 'Imperial', geometry: BA, fixedFlutes: 6 },
  { file: 'FRT V5 Corner Radius.csv', category: V5, system: 'Imperial', geometry: CR, fixedFlutes: 6 },
  { file: 'MET V5 Square.csv', category: V5, system: 'Metric', geometry: SQ, fixedFlutes: 6 },
  { file: 'MET V5 Ball.csv', category: V5, system: 'Metric', geometry: BA, fixedFlutes: 6 },
  { file: 'MET V5 Corner Radius.csv', category: V5, system: 'Metric', geometry: CR, fixedFlutes: 6 },
  // ---- HY5 (flutes 4) ----
  { file: 'FRT HY5 Square End.csv', category: HY5, system: 'Imperial', geometry: SQ, fixedFlutes: 4 },
  { file: 'FRT HY5 Corner Radius.csv', category: HY5, system: 'Imperial', geometry: CR, fixedFlutes: 4 },
  { file: 'MET HY5 Square Endmills.csv', category: HY5, system: 'Metric', geometry: SQ, fixedFlutes: 4 },
  { file: 'MET Hy5 Corner Radius.csv', category: HY5, system: 'Metric', geometry: CR, fixedFlutes: 4 },
  // ---- F45 (6-flute finisher; header also states 6) ----
  { file: 'FRT F45 Square End.csv', category: F45, system: 'Imperial', geometry: SQ, fixedFlutes: 6 },
  { file: 'FRT - F45 Corner Radius.csv', category: F45, system: 'Imperial', geometry: CR, fixedFlutes: 6 },
  { file: 'MET F45 Square.csv', category: F45, system: 'Metric', geometry: SQ, fixedFlutes: 6 },
  { file: 'MET F45 Corner Radius.csv', category: F45, system: 'Metric', geometry: CR, fixedFlutes: 6 },
  // ---- AxMill (flutes from header 2/3) ----
  { file: 'FRT Square End Axmills.csv', category: AX, system: 'Imperial', geometry: SQ },
  { file: 'FRT Ball Axmills.csv', category: AX, system: 'Imperial', geometry: BA },
  { file: 'FRT Corner Radius Axmills.csv', category: AX, system: 'Imperial', geometry: CR },
  { file: 'FRT Square Chipbreaker Axmills.csv', category: AX, system: 'Imperial', geometry: SQ },
  { file: 'FRT Square Necked Axmills.csv', category: AX, system: 'Imperial', geometry: SQ },
  { file: 'FRT Ball Necked Axmills.csv', category: AX, system: 'Imperial', geometry: BA },
  { file: 'FRT Corner Radius Necked Axmills.csv', category: AX, system: 'Imperial', geometry: CR },
  { file: 'MET Square Axmills.csv', category: AX, system: 'Metric', geometry: SQ },
  { file: 'MET Axmills CR.csv', category: AX, system: 'Metric', geometry: CR },
  { file: 'MET SQ Chipbreaker Axmills.csv', category: AX, system: 'Metric', geometry: SQ },
  { file: 'MET Corner Chipbreaker Axmills.csv', category: AX, system: 'Metric', geometry: CR },
  // ---- Roughers (explicit Flutes column) ----
  { file: 'FRT Coarse Pitch Roughers.csv', category: RO, system: 'Imperial' },
  { file: 'FRT - Medium Pitch Roughers.csv', category: RO, system: 'Imperial' },
  { file: 'FRT - Fine Pitch Roughers.csv', category: RO, system: 'Imperial' },
  { file: 'MET Coarse Pitch Rougher.csv', category: RO, system: 'Metric' },
  { file: 'MET Medium Pitch Roughers.csv', category: RO, system: 'Metric' },
  { file: 'MET Fine Pitch Rougher.csv', category: RO, system: 'Metric' },
  // ---- Mold Mills (necked; flutes from header where present) ----
  { file: 'FR Mold Mill CR Necked.csv', category: MO, system: 'Imperial', geometry: CR },
  { file: 'FRT Corner Radius Mold Mills Long.csv', category: MO, system: 'Imperial', geometry: CR },
  { file: 'FRT Mold Mills Square Necked.csv', category: MO, system: 'Imperial', geometry: SQ },
  { file: 'FRT Mold Mills Necked Ball.csv', category: MO, system: 'Imperial', geometry: BA },
  { file: 'MET Mold Mills Ball Necked.csv', category: MO, system: 'Metric', geometry: BA },
  { file: 'MET Ball Necked Extended Mold Mills.csv', category: MO, system: 'Metric', geometry: BA },
  // ---- Twistermills ----
  { file: 'FRT Twistermills.csv', category: TW, system: 'Imperial' },
  { file: 'MET Twistermill.csv', category: TW, system: 'Metric' },
  // ---- Hypermills (2-flute) ----
  { file: 'FRT Hypermills.csv', category: HY, system: 'Imperial', fixedFlutes: 2 },
  { file: 'MET Hypermills.csv', category: HY, system: 'Metric', fixedFlutes: 2 },
  // ---- Alumazips (2-flute) ----
  { file: 'FRT Alumazips.csv', category: AL, system: 'Imperial', fixedFlutes: 2 },
  { file: 'MET Alumazips.csv', category: AL, system: 'Metric', fixedFlutes: 2 },

  // ==== HIGH PERFORMANCE ROUTERS — 1-flute lines (all Uncoated) ====
  { file: '202 V Flute Straight Cut.csv', category: 'r-v-flute-straight', system: 'Imperial', fixedFlutes: 1 },
  { file: '203 O Flute Straight.csv', category: 'r-o-flute-straight', system: 'Imperial', fixedFlutes: 1 },
  { file: '203 1 Flute O Flute Straight Metric.csv', category: 'r-o-flute-straight', system: 'Metric', fixedFlutes: 1 },
  { file: '204 O Flute Straight Edge Rounding.csv', category: 'r-o-flute-straight-edge-rounding', system: 'Imperial', fixedFlutes: 1 },
  { file: '205 O Flut Spiral Edge Rounding.csv', category: 'r-o-flute-spiral-edge-rounding', system: 'Imperial', fixedFlutes: 1 },
  { file: '1FL O Upcut Spiral.csv', category: 'r-o-flute-upcut-spiral', system: 'Imperial', fixedFlutes: 1 },
  { file: '1FL O Upcut Spiral Metric.csv', category: 'r-o-flute-upcut-spiral', system: 'Metric', fixedFlutes: 1 },
  { file: '1FL O Downcut Spiral.csv', category: 'r-o-flute-downcut-spiral', system: 'Imperial', fixedFlutes: 1 },
  { file: '1FL O Downcut Spiral Metric.csv', category: 'r-o-flute-downcut-spiral', system: 'Metric', fixedFlutes: 1 },
  { file: '1FL STD Upcut.csv', category: 'r-upcut-spiral', system: 'Imperial', fixedFlutes: 1 },
  { file: '212 1FL Upcut Sprial Hard Plastic Metric.csv', category: 'r-upcut-spiral', system: 'Metric', fixedFlutes: 1, fixedApplication: 'Hard Plastic' },
  { file: '1FL STD Downcut.csv', category: 'r-downcut-spiral', system: 'Imperial', fixedFlutes: 1 },
  { file: '213 1FL Downcut Sprial Hard Plastic Metric.csv', category: 'r-downcut-spiral', system: 'Metric', fixedFlutes: 1, fixedApplication: 'Hard Plastic' },
  { file: '216 1FL Veining Bit.csv', category: 'r-veining-bits', system: 'Imperial', fixedFlutes: 1 },
  { file: '217 1FL Compression.csv', category: 'r-compression', system: 'Imperial', fixedFlutes: 1 },
  { file: '217 1FL Compression Metric.csv', category: 'r-compression', system: 'Metric', fixedFlutes: 1 },
  { file: '218 1FL Ball Compression.csv', category: 'r-ball-compression', system: 'Imperial', fixedFlutes: 1 },
  { file: '219 1FL Mortise Compression.csv', category: 'r-mortise-compression', system: 'Imperial', fixedFlutes: 1 },
  { file: '219 1FL Mortise Compression Metric.csv', category: 'r-mortise-compression', system: 'Metric', fixedFlutes: 1 },
  { file: 'OFX FR UPCUT.csv', category: 'r-ofx-upcut', system: 'Imperial', fixedFlutes: 1 },
  { file: 'OFX MT Upcut.csv', category: 'r-ofx-upcut', system: 'Metric', fixedFlutes: 1 },
  { file: 'OFX FR Downcut.csv', category: 'r-ofx-downcut', system: 'Imperial', fixedFlutes: 1 },
  { file: 'OFX MT Downcut.csv', category: 'r-ofx-downcut', system: 'Metric', fixedFlutes: 1 },

  // ==== 2-FLUTE ROUTER LINES (all Uncoated) ====
  { file: '233 2FL Up Spiral HP.csv', category: 'r2-upcut-spiral', system: 'Imperial', fixedFlutes: 2 },
  { file: '233 2FL Up Spiral HP Metric.csv', category: 'r2-upcut-spiral', system: 'Metric', fixedFlutes: 2 },
  { file: '234 2FL Down Spiral HP.csv', category: 'r2-downcut-spiral', system: 'Imperial', fixedFlutes: 2 },
  { file: '234 2FL Down Spiral HP Metric.csv', category: 'r2-downcut-spiral', system: 'Metric', fixedFlutes: 2 },
  { file: '237 2FL Upcut Slow Spiral.csv', category: 'r2-upcut-slow', system: 'Imperial', fixedFlutes: 2 },
  { file: '238 2FL Downcut Slow Spiral.csv', category: 'r2-downcut-slow', system: 'Imperial', fixedFlutes: 2 },
  { file: '235 2FL O Flute Upcut Slow Spiral.csv', category: 'r2-o-upcut-slow', system: 'Imperial', fixedFlutes: 2 },
  { file: '235 2FL O Flute Upcut Slow Spiral Metric.csv', category: 'r2-o-upcut-slow', system: 'Metric', fixedFlutes: 2 },
  { file: '236 2FL O Flute Downcut Slow Spiral.csv', category: 'r2-o-downcut-slow', system: 'Imperial', fixedFlutes: 2 },
  { file: '236 2FL O Flute Downcut Slow Spiral Metric.csv', category: 'r2-o-downcut-slow', system: 'Metric', fixedFlutes: 2 },
  { file: '239 2FL UP Spiral Chipbreaker.csv', category: 'r2-upcut-chipbreaker', system: 'Imperial', fixedFlutes: 2 },
  { file: '239 2FL UP Spiral Chipbreaker Metric.csv', category: 'r2-upcut-chipbreaker', system: 'Metric', fixedFlutes: 2 },
  { file: '240 2FL Down Spiral Chipbreaker.csv', category: 'r2-downcut-chipbreaker', system: 'Imperial', fixedFlutes: 2 },
  { file: '240 2FL Down Spiral Chipbreaker Metric.csv', category: 'r2-downcut-chipbreaker', system: 'Metric', fixedFlutes: 2 },
  { file: '231 2FL Up High Impact.csv', category: 'r2-upcut-high-impact', system: 'Imperial', fixedFlutes: 2 },
  { file: '232 2FL Downcut High Impact.csv', category: 'r2-downcut-high-impact', system: 'Imperial', fixedFlutes: 2 },
  { file: '241 2FL Upcut Chipbreaker High Impact.csv', category: 'r2-upcut-chipbreaker-hi', system: 'Imperial', fixedFlutes: 2 },
  { file: '242 2FL Downcut Chipbreaker High Impact_copy.csv', category: 'r2-downcut-chipbreaker-hi', system: 'Imperial', fixedFlutes: 2 },
  { file: '2FL Compression.csv', category: 'r2-compression', system: 'Imperial', fixedFlutes: 2 },
  { file: '243 2FL Compression GW Metric.csv', category: 'r2-compression', system: 'Metric', fixedFlutes: 2 },
  { file: '245 2FL Mortise Compression GW.csv', category: 'r2-mortise-compression', system: 'Imperial', fixedFlutes: 2 },
  { file: '245 2FL Mortise Compression GW Metric.csv', category: 'r2-mortise-compression', system: 'Metric', fixedFlutes: 2 },
  { file: '246 2FL Chipbreaker Compression.csv', category: 'r2-chipbreaker-compression', system: 'Imperial', fixedFlutes: 2 },
  { file: '246 2FL Chipbreaker Compression Metric.csv', category: 'r2-chipbreaker-compression', system: 'Metric', fixedFlutes: 2 },
  { file: '229 2FL Up Plunge GW.csv', category: 'r2-up-plunge', system: 'Imperial', fixedFlutes: 2 },
  { file: '229 2FL Up Plunge GW Metric.csv', category: 'r2-up-plunge', system: 'Metric', fixedFlutes: 2 },
  { file: '230 Downcut Spiral Fishtail.csv', category: 'r2-downcut-fishtail', system: 'Imperial', fixedFlutes: 2 },
  { file: '230 Downcut Spiral Fishtail Metric.csv', category: 'r2-downcut-fishtail', system: 'Metric', fixedFlutes: 2 },
  { file: '222 2FL Straight Cut Plunge HP.csv', category: 'r2-straight-plunge', system: 'Imperial', fixedFlutes: 2 },
  { file: '222 2FL Straight Cut Plunge HP Metric.csv', category: 'r2-straight-plunge', system: 'Metric', fixedFlutes: 2 },
  { file: '225 Shear V Bottom.csv', category: 'r2-shear-v-bottom', system: 'Imperial', fixedFlutes: 2 },
  // NOTE: the vendor's 224 files have swapped contents — the "Metric" file holds
  // imperial data (803-*) and the plain file holds metric (903-*). Assigned by content.
  { file: '224 2FL V Flute Edge Rounding Metric.csv', category: 'r2-v-edge-rounding', system: 'Imperial', fixedFlutes: 2 },
  { file: '224 2FL V Flute Edge Rounding.csv', category: 'r2-v-edge-rounding', system: 'Metric', fixedFlutes: 2 },
  { file: '226 2FL Straight O Edge Round.csv', category: 'r2-o-edge-rounding', system: 'Imperial', fixedFlutes: 2 },
  { file: '226 2FL Straight O Edge Round Metric.csv', category: 'r2-o-edge-rounding', system: 'Metric', fixedFlutes: 2 },
  { file: '248 2FL Straight Rout and Chamfer.csv', category: 'r2-rout-chamfer', system: 'Imperial', fixedFlutes: 2 },
  { file: '249 2FL Upcut Bottom Surface.csv', category: 'r2-upcut-bottom-surface', system: 'Imperial', fixedFlutes: 2 },
  { file: '249 2FL Upcut Bottom Surface Metric.csv', category: 'r2-upcut-bottom-surface', system: 'Metric', fixedFlutes: 2 },

  // ==== REAMERS (explicit Flutes column; part number in "Uncoated") ====
  { file: 'FRT 45 Degree Reamer.csv', category: 'rm-45-reamers', system: 'Imperial' },

  // ==== STANDARD CARBIDE DRILLS (Uncoated/PowerA; point angle in header or "Point Angle" col) ====
  { file: 'FRT Jobber Drills.csv', category: 'dr-jobber-drills', system: 'Imperial' },
  { file: 'MET 2 Flute Jobber.csv', category: 'dr-jobber-drills', system: 'Metric', fixedFlutes: 2 },
  { file: 'MET 3 Flute Jobber.csv', category: 'dr-jobber-drills', system: 'Metric', fixedFlutes: 3 },
  { file: 'FRT Stub Drills.csv', category: 'dr-stub-drills', system: 'Imperial' },
  { file: 'MET Stub Drill.csv', category: 'dr-stub-drills', system: 'Metric', fixedFlutes: 2 },
  { file: 'FRT Straight Flute Drills.csv', category: 'dr-straight-flute-drills', system: 'Imperial' },
  { file: 'FRT Spade Drills.csv', category: 'dr-spade-drills', system: 'Imperial' },
  { file: 'MET Spade Drill.csv', category: 'dr-spade-drills', system: 'Metric', fixedFlutes: 2 },
  { file: 'FRT NC Spotting Drills.csv', category: 'dr-nc-spotting-drills', system: 'Imperial' },
  { file: 'MET NC Spotting Drill.csv', category: 'dr-nc-spotting-drills', system: 'Metric' },
  { file: 'FRT Drill and Countersink.csv', category: 'dr-drill-countersink', system: 'Imperial' },
  { file: 'MET Drill and Countersink.csv', category: 'dr-drill-countersink', system: 'Metric' },
  { file: 'MET Medium Length Drill.csv', category: 'dr-medium-length-drills', system: 'Metric', fixedFlutes: 2 },

  // ==== HURRICANE DRILLS (HP; 2FL, 140° point, 30° helix; coolant-through facet in header) ====
  { file: 'Hurricane 3xD.csv', category: 'dr-hurricane-3xd', system: 'Imperial', fixedFlutes: 2, fixedPointAngle: 140, fixedHelix: 30 },
  { file: 'Hurricane 5xD.csv', category: 'dr-hurricane-5xd', system: 'Imperial', fixedFlutes: 2, fixedPointAngle: 140, fixedHelix: 30 },
  { file: 'Hurricane 8xD.csv', category: 'dr-hurricane-8xd', system: 'Imperial', fixedFlutes: 2, fixedPointAngle: 140, fixedHelix: 30 },

  // ==== CARBIDE BURS — shapes SA–SN (cut style in header: Single/Double/Aluma/Diamond/Chipbreaker) ====
  { file: 'FRT SA Burs.csv', category: 'b-sa', system: 'Imperial' }, { file: 'MET SA Bur.csv', category: 'b-sa', system: 'Metric' },
  { file: 'FRT SB Burs.csv', category: 'b-sb', system: 'Imperial' }, { file: 'MET SB Bur.csv', category: 'b-sb', system: 'Metric' },
  { file: 'FRT SC Burs.csv', category: 'b-sc', system: 'Imperial' }, { file: 'MET SC Bur.csv', category: 'b-sc', system: 'Metric' },
  { file: 'FRT SD Burs.csv', category: 'b-sd', system: 'Imperial' }, { file: 'MET SD Bur.csv', category: 'b-sd', system: 'Metric' },
  { file: 'FRT SE Burs.csv', category: 'b-se', system: 'Imperial' }, { file: 'MET SE Bur.csv', category: 'b-se', system: 'Metric' },
  { file: 'FRT SF Burs.csv', category: 'b-sf', system: 'Imperial' }, { file: 'MET SF Bur.csv', category: 'b-sf', system: 'Metric' },
  { file: 'FRT SG Burs.csv', category: 'b-sg', system: 'Imperial' }, { file: 'MET SG Bur.csv', category: 'b-sg', system: 'Metric' },
  { file: 'FRT SH Burs.csv', category: 'b-sh', system: 'Imperial' }, { file: 'MET SH Bur.csv', category: 'b-sh', system: 'Metric' },
  { file: 'FRT SJ Burs.csv', category: 'b-sj', system: 'Imperial' }, { file: 'MET SJ Bur.csv', category: 'b-sj', system: 'Metric' },
  { file: 'FRT SK Burs.csv', category: 'b-sk', system: 'Imperial' }, { file: 'MET SK Bur.csv', category: 'b-sk', system: 'Metric' },
  { file: 'FRT SL Burs.csv', category: 'b-sl', system: 'Imperial' }, { file: 'MET SL Burs.csv', category: 'b-sl', system: 'Metric' },
  { file: 'FRT SM Burs.csv', category: 'b-sm', system: 'Imperial' }, { file: 'MET SM Burs.csv', category: 'b-sm', system: 'Metric' },
  { file: 'FRT SN Burs.csv', category: 'b-sn', system: 'Imperial' }, { file: 'MET SN Burs.csv', category: 'b-sn', system: 'Metric' },

  // ==== TIRE BURS / DIEMILLS / FIBERGLASS ROUTERS ====
  { file: 'FRT Tire Burs.csv', category: 'b-tire-burs', system: 'Imperial' }, { file: 'MET Tire Burs.csv', category: 'b-tire-burs', system: 'Metric' },
  { file: 'FRT Diemills.csv', category: 'b-diemills', system: 'Imperial' },
  { file: 'FRT Piloted Diemills.csv', category: 'b-piloted-diemills', system: 'Imperial' },
  { file: 'FRT Fiberglass Routers.csv', category: 'b-fiberglass-routers', system: 'Imperial', fixedFlutes: 1 },
  { file: 'MET Fiberglass Routers.csv', category: 'b-fiberglass-routers', system: 'Metric', fixedFlutes: 1 },
];

// Exact-duplicate "(1)" exports intentionally skipped.
export const SKIPPED = [
  'FR Mold Mill CR Necked (1).csv', 'FRT Corner Radius Mold Mills Long (1).csv',
  'FRT Corner Radius Necked Axmills (1).csv', 'MET Medium Pitch Roughers (1).csv', 'MET SQ Chipbreaker Axmills (1).csv',
  'FRT 45 Degree Reamer (1).csv', 'FRT NC Spotting Drills (1).csv',
  'FRT SA Burs (1).csv', 'FRT SB Burs (1).csv', 'FRT Fiberglass Routers (1).csv',
];
